#!/bin/bash
#

clear

g++ -Wall         \
    -Wextra       \
    -Wshadow      \
    -pedantic     \
    -Werror       \
    -std=c++17    \
    -pthread      \
    -o futureTest \
    futureTest.cc

if [ $? == 0 ]
then
    ./futureTest
    rm futureTest
fi
