#!/bin/bash
#

g++ -std=c++14      \
    -Wall           \
    -Wextra         \
    -Wshadow        \
    -Werror         \
    -o lambdaSyntax \
    lambdaSyntax.cc

./lambdaSyntax

rm lambdaSyntax
