#!/bin/bash
#

clear

g++ -Wall         \
    -Wextra       \
    -Wshadow      \
    -Werror       \
    -pedantic     \
    -pthread      \
    -o testAtomic \
    testAtomic.cc

# if it compiles run it five hundred times and get
# a count of the number of each outcome

if [ $? == 0 ]
then

    yes | head -500 | xargs -I {} ./testAtomic |    \
    grep thread | awk '{print $2}' | sed 's/^#//' | \
    awk '{arr[$1]++} END {for (key in arr) {print "[" key "] count " arr[key]}}'

    rm testAtomic

fi
