#!/bin/bash
#

g++ --std=c++17              \
    -Wall                    \
    -Werror                  \
    -Wshadow                 \
    VectorImplementation.cc  \
    -o VectorImplementation

if [ $? == 0 ]; then
    ./VectorImplementation
    # can be used to pribt out the strings in the binary
    #cat Strings | c++filt -t

    # clean up
    rm VectorImplementation
fi
