#!/bin/bash
#

clear

g++ -Wall         \
    -Wextra       \
    -Wshadow      \
    -Werror       \
    -pedantic     \
    -pthread      \
    -o virtual    \
    virtual.cc

# if it compiles run it five hundred times and get
# a count of the number of each outcome

if [ $? == 0 ]
then

    ./virtual
    rm virtual

fi
