#!/bin/bash
#

g++ --std=c++17 \
    -Wall       \
    -Werror     \
    -Wshadow    \
    Strings.cc  \
    -o Strings

if [ $? == 0 ]; then
    ./Strings
    # can be used to pribt out the strings in the binary
    #cat Strings | c++filt -t

    # clean up
    rm Strings
fi
