#!/bin/bash
#

clear

# compile
g++ -std=c++20 -Wall           \
               -Wextra         \
               -Wpedantic      \
               -Wshadow        \
               -Werror         \
               -pthread        \
               -o MyFirstMutex \
               MyFirstMutex.cc

# if compliation was sucessful then run
# the program
if [ $? == 0 ];
then
    ./MyFirstMutex | c++filt -t
fi
